### ISSUE TITLE
registration seems to be broken on iPhone, Safari

### ISSUE THREAD

**Issue by alexm** [Act-Conferences/ye2015#7]
Alex Balhatchet on [Twitter](https://twitter.com/kaokun/status/589745555103952896):

> registration seems to be broken on iPhone, Safari. If I press the blue button I end up back on that page.

**Comment by JJ** [comment]
¿Es un problema nuestro o de todo ACT?

**Comment by alexm** [comment]
The problem is present in meis/act-responsive@fe20ba9a44c3254b6f71a21c01b49b9d6e833765 so all Act instances based on those templates have this issue too.
